services:
    - type: web
      name: brief_client
      build:
        name: brief_client
        context: ./client
        dockerfile: Dockerfile
        target: production
      env:
        - REACT_APP_API_URL=brief_server:5000
      routes:
        - path: /
          command: npm start
      volumes:
        - type: bind
          source: ./client
          target: /usr/src/app
        - type: volume
          source: node_modules
          target: /usr/src/app/node_modules

    - type: web
      name: brief_server
      build:
        name: brief_server
        context: ./server
      env:
        - DB_NAME=economics
        - DB_USER=economics
        - DB_PASSWORD=root
        - DB_PORT=5432
        - DB_HOST=brief_database
        - DB_CONNECTION_RETRIES=10
        - DB_CONNECTION_RETRIES_DELAY=5000
        - NODE_ENV=production
      command: npm run start
      healthCheck:
        httpPath: /api/ping
        timeout: 10s
        interval: 1m30s
        unhealthyThreshold: 3
        startPeriod: 40s
      volumes:
        - type: bind
          source: ./server
          target: /usr/src/app
        - type: volume
          source: node_modules
          target: /usr/src/app/node_modules
      envVars:
        DB_NAME: economics
        DB_USER: economics
        DB_PASSWORD: root
        DB_PORT: '5432'
        DB_HOST: brief_database

    - type: web
      name: brief_database
      image: postgres
      env:
        - POSTGRES_USER=economics
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=economics
      ports:
        - 5001:5432
      volumes:
        - type: volume
          source: postgres-data
          target: /var/lib/postgresql/data

#volumes:
#  node_modules:
#  postgres-data:
